sources:
  - name: raw
    schema: gz_raw_data #où se situe la table dans BQ
    description: greenwez raw data source
    tables:
      - name: sales
        identifier: raw_gz_sales #Quel est le nom exacte de la table dans BQ
        description: sales of greewneez / we have one row per product_id found in each order_id
        columns:
          - name: "(orders_id || '-' || pdt_id)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: product
        identifier: raw_gz_product
        description: purchase_price by products_id
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique

      - name: ship
        identifier: raw_gz_ship
        description: shipment fee by orders_id
        columns:
          - name: orders_id
            description: primary key of the table
            tests:
              - unique

      - name: adwords
        identifier: raw_gz_adwords #Quel est le nom exacte de la table dans BQ
        description: adwords campaign metrics
        columns:
          - name: "(date_date|| '-' || paid_source || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: bing
        identifier: raw_gz_bing #Quel est le nom exacte de la table dans BQ
        description: bing campaign metrics
        columns:
          - name: "(date_date|| '-' || paid_source || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: criteo
        identifier: raw_gz_criteo #Quel est le nom exacte de la table dans BQ
        description: criteo campaign metrics
        columns:
          - name: "(date_date|| '-' || paid_source || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name: facebook
        identifier: raw_gz_facebook #Quel est le nom exacte de la table dans BQ
        description: facebook campaign metrics
        columns:
          - name: "(date_date|| '-' || paid_source || '-' || campaign_key)"
            description: primary key of the table
            tests:
              - unique
              - not_null